# Generated by Django 4.0.1 on 2022-03-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='blog',
            field=models.ManyToManyField(related_name='treasure', to='blog.Blog'),
        ),
    ]
