# Generated by Django 4.0.1 on 2022-03-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='event',
            field=models.ManyToManyField(related_name='treasure', to='event.Event'),
        ),
    ]
