# Generated by Django 4.0.1 on 2022-03-03 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Şərh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tariix')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('content', models.CharField(max_length=5000, verbose_name='Content')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date creation')),
                ('drafted', models.BooleanField(default=False, verbose_name='drafted')),
                ('views', models.IntegerField(default=0, verbose_name='views')),
                ('starts_at', models.DateTimeField(verbose_name='Başlanma tarixi')),
                ('ends_at', models.DateTimeField(verbose_name='Sonlanma tarixi')),
                ('like_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='liked_event', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_created',),
                'abstract': False,
            },
        ),
    ]
