# Generated by Django 4.0.1 on 2022-03-03 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('founded_at', models.DateField(blank=True, null=True, verbose_name='Date created')),
                ('workers', models.ManyToManyField(blank=True, related_name='works_at', to=settings.AUTH_USER_MODEL, verbose_name='workers')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('content', models.CharField(max_length=5000, verbose_name='Content')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date creation')),
                ('drafted', models.BooleanField(default=False, verbose_name='drafted')),
                ('views', models.IntegerField(default=0, verbose_name='views')),
                ('dead_line', models.DateField(null=True, verbose_name='Date expiration (YYYY-MM-DD)')),
                ('freelance', models.BooleanField(verbose_name='Remote')),
                ('contact', models.CharField(max_length=128, verbose_name='Contact')),
                ('min_salary', models.PositiveIntegerField(verbose_name='Min salary')),
                ('like_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancy.employer')),
                ('likes', models.ManyToManyField(blank=True, null=True, related_name='liked_vacancy', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'vacancy',
                'verbose_name_plural': 'vacancies',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Şərh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tariix')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v_comments', to=settings.AUTH_USER_MODEL, verbose_name='müəllif')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vacancy.vacancy')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
