# Generated by Django 4.0.1 on 2022-03-24 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1024, verbose_name='content')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date creation')),
                ('like_count', models.IntegerField(default=0, verbose_name='like count')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancy_comments', to=settings.AUTH_USER_MODEL)),
                ('likers', models.ManyToManyField(blank=True, related_name='liked_vacancy_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('founded_at', models.DateField(blank=True, null=True, verbose_name='Date created')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workers', models.ManyToManyField(blank=True, related_name='works_at', to=settings.AUTH_USER_MODEL, verbose_name='workers')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('content', models.CharField(max_length=5000, verbose_name='Content')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date creation')),
                ('drafted', models.BooleanField(default=False, verbose_name='drafted')),
                ('views', models.IntegerField(default=0, verbose_name='views')),
                ('dead_line', models.DateField(null=True, verbose_name='Date expiration (YYYY-MM-DD)')),
                ('freelance', models.BooleanField(verbose_name='Remote')),
                ('contact', models.CharField(max_length=128, verbose_name='Contact')),
                ('min_salary', models.PositiveIntegerField(verbose_name='Min salary')),
                ('like_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL)),
                ('comments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='for_vacancies', to='vacancy.comment')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancy.employer')),
                ('likes', models.ManyToManyField(related_name='liked_vacancy', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('viewers', models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vacancy',
                'verbose_name_plural': 'vacancies',
            },
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
