# Generated by Django 4.0.1 on 2022-04-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='added_by',
        ),
    ]
