# Generated by Django 4.0.1 on 2022-03-21 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_alter_news_options_alter_news_image_alter_news_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='viewers',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newss', to=settings.AUTH_USER_MODEL),
        ),
    ]
